<a href="https://colab.research.google.com/github/19PA1A0493/PYTHON-BASICS/blob/master/numpay_practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[9,8,7]])
b=np.array([[0,0,1],[2,2,2],[3,3,3]])
m=(a*b)
n=(a+b)
v=(a-b)
c=(a/b)
print(m)
print(n)
print(v)
print(c)


[[ 0  0  3]
 [ 8 10 12]
 [27 24 21]]
[[ 1  2  4]
 [ 6  7  8]
 [12 11 10]]
[[1 2 2]
 [2 3 4]
 [6 5 4]]
[[       inf        inf 3.        ]
 [2.         2.5        3.        ]
 [3.         2.66666667 2.33333333]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in true_divide
  import sys


In [21]:
import numpy as np
a=np.array([[1,2,3,4,5,6],[7,8,9,0,1,6]])
print(a)
s=np.hsplit(a,3)
print(s)
d=np.vsplit(a,2)
print(d)


[[1 2 3 4 5 6]
 [7 8 9 0 1 6]]
[array([[1, 2],
       [7, 8]]), array([[3, 4],
       [9, 0]]), array([[5, 6],
       [1, 6]])]
[array([[1, 2, 3, 4, 5, 6]]), array([[7, 8, 9, 0, 1, 6]])]


In [39]:
import numpy as np
a=np.floor(5*np.random.random((2,2)))
b=np.floor(5*np.random.random((2,2)))
c=np.vstack((a,b))
print(c)
v=np.hstack((a,b))
print(v)

[[0. 1.]
 [3. 1.]
 [3. 1.]
 [0. 2.]]
[[0. 1. 3. 1.]
 [3. 1. 0. 2.]]


In [44]:
import numpy as np
a=np.floor(10*np.random.random((3,6)))
s=a.reshape((2,9))
f=a.resize((18,1))
print(s)
print(f)

[[8. 6. 5. 6. 3. 7. 1. 5. 7.]
 [8. 9. 4. 0. 2. 8. 0. 4. 0.]]
None


In [45]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[1,2,3]])
c=a.T
print(c)

[[1 4 1]
 [2 5 2]
 [3 6 3]]


In [46]:
import numpy as np
a=np.floor(10*np.random.random((6,4)))
c=a.ravel()
v=a.T
print(c)
print(v)

[6. 7. 0. 7. 8. 5. 3. 9. 0. 1. 7. 8. 0. 8. 7. 2. 2. 9. 0. 1. 7. 7. 6. 0.]
[[6. 8. 0. 0. 2. 7.]
 [7. 5. 1. 8. 9. 7.]
 [0. 3. 7. 7. 0. 6.]
 [7. 9. 8. 2. 1. 0.]]


In [54]:
import numpy as np
a=np.arange(12).reshape(4,3)**2
print(a)
print(a[1:3])
print(a[2:3])
print(a[ :2])


[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]
[[ 9 16 25]
 [36 49 64]]
[[36 49 64]]
[[ 0  1  4]
 [ 9 16 25]]


In [56]:
import numpy as np
a=np.arange(12).reshape(4,3)**2
print(a)
for i in a.flat:
  print(i)

[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]
0
1
4
9
16
25
36
49
64
81
100
121


In [58]:
import numpy as np
a=np.arange(18).reshape(6,3)**2
print(a)
for i in a:
  print(i)

[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]
 [144 169 196]
 [225 256 289]]
[0 1 4]
[ 9 16 25]
[36 49 64]
[ 81 100 121]
[144 169 196]
[225 256 289]
